import 'package:supabase_flutter/supabase_flutter.dart';
import '../../core/constants/supabase_constants.dart';
import '../../core/network/supabase_client.dart';
import '../../models/store_model.dart';

class StoresProvider {
  final SupabaseClient _client;

  StoresProvider({SupabaseClient? client})
      : _client = client ?? supabaseClient;

  Future<Store?> getStoreById(String storeId) async {
    final response = await _client
        .from(SupabaseConstants.storesTable)
        .select()
        .eq('id', storeId)
        .maybeSingle();

    if (response == null) return null;
    return Store.fromMap(response);
  }

  Future<List<Store>> getStores() async {
    final response = await _client
        .from(SupabaseConstants.storesTable)
        .select()
        .eq('is_approved', true);

    return (response as List)
        .map((item) => Store.fromMap(item as Map<String, dynamic>))
        .toList();
  }

  Future<String> createStore(Store store) async {
    final map = store.toMap();
    // Remove empty id if generated by database
    if (store.storeId.isEmpty) {
      map.remove('id');
    }
    final response = await _client
        .from(SupabaseConstants.storesTable)
        .insert(map)
        .select('id')
        .single();

    return response['id'].toString();
  }

  Future<void> updateStore(String storeId, Map<String, dynamic> data) async {
    await _client
        .from(SupabaseConstants.storesTable)
        .update(data)
        .eq('id', storeId);
  }

  Future<void> deleteStore(String storeId) async {
    await _client
        .from(SupabaseConstants.storesTable)
        .delete()
        .eq('id', storeId);
  }
}
